version: '3'
services:
  postgres:
    container_name: postgres
    image: docker-artifacts.ua-ecm.com/postgresql:10.5
    volumes:
      - './schema/db-init.sh:/docker-entrypoint-initdb.d/db-init.sh'
    ports:
      - '5432:5432'
  db-migrate:
    container_name: db-migrate
    image: docker-artifacts.ua-ecm.com/liquibase:3.5
    volumes:
      - '.:/src'
    command:
      - /bin/bash
      - -c
      - |
        /src/wait-for-it.sh postgres:5432 -- echo "postgres running"
        liquibase \
          --driver=org.postgresql.Driver \
          --logLevel=debug \
          --url=jdbc:postgresql://postgres:5432/jumpin \
          --username=postgres \
          --defaultSchemaName=hop \
          --changeLogFile=/src/schema/dev.yaml \
          update
    depends_on:
      - postgres
